var event = {
    '1980': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1981': ["Iran Iraq war continues", "OPEC agreement for $32/bbl", "Exxon withdraws from Libya", "Windfall profits tax reduced."],
    '1982': ["Iran Iraq war continues", "Damascus closes Iraqs export pipeline of 400,000bbl/d ", "U.S. boycotts Libyan crude.", "Windfall profits tax reduced."],
    '1983': ["Iran Iraq war continues", "NYMEX  starts trading in crude oil futures", "U.S. boycotts Libyan crude.", "Windfall profits tax reduced."],
    '1984': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1985': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1986': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1987': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1988': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1989': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1990': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1991': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1991': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1992': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1993': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1994': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1995': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1996': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1999': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '1999': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2000': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2001': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2002': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2003': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2004': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2005': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2006': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2007': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2008': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2009': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2010': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2011': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2012': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2013': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2014': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2015': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2016': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2017': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],
    '2018': ["Saudi Aramco reverts to state ownership ", "Supply shock ", "Collapse of OPEC's  pricing structure", ""],


};